//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public int ContractId { get; set; }
        public System.DateTime DateStart { get; set; }
        public int Quantity { get; set; }
        public string Type { get; set; }
        public string Payment { get; set; }
        public int ClientId { get; set; }
        public int TrainerId { get; set; }
        public int ServiceId { get; set; }
        public System.DateTime DateEnd { get; set; }
        public double Sum { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Trainer Trainer { get; set; }
        public virtual Service Service { get; set; }
    }
}
